### ISSUE TITLE
uncaught errors from ssh-key-to-pem

### ISSUE THREAD

**Issue by keis** [mafintosh/ghsign#3]
trying to use `friends` I'm seeing some non rsa/dsa keys being passed into ssh-key-to-pem via this module which causes a error to be thrown.

in verify and other places with a single key I would expect the error in the callback when mapping over the keys I think it would make sense to ignore that key and continue searching.

**Comment by keis** [comment]
specifically what's crashing seems to be
`ghsign.publicKeys('okket', function () {})`

**Comment by mafintosh** [comment]
pretty sure this is fixed in master :) could you try the latest version and see if i'm right?

**Comment by keis** [comment]
yep. it's working now :+1:

**Comment by mafintosh** [comment]
:+1:
